# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 05:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(verbose_name='date started')),
                ('completed', models.BooleanField(verbose_name='completed')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1letters', models.CharField(max_length=7)),
                ('p2letters', models.CharField(max_length=7)),
                ('board', models.CharField(max_length=450)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.GameState'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordsgame_first_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordsgame_second_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
