# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160909_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
