# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='draw_pile',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
