# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160910_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_move',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last move'),
        ),
    ]
