# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_last_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
            preserve_default=False,
        ),
    ]
