# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p2_first',
            field=models.BooleanField(default=False, verbose_name='player-2-firstness'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='completed',
            field=models.BooleanField(verbose_name='completedness'),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_move',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of last move'),
        ),
        migrations.AlterField(
            model_name='game',
            name='public',
            field=models.BooleanField(verbose_name='publicness'),
        ),
    ]
