# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20160911_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p1_turn',
            field=models.BooleanField(default=True, verbose_name='player-1-turniness'),
            preserve_default=False,
        ),
    ]
