# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_gamestate_last_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='p1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='p2_score',
            field=models.IntegerField(default=0),
        ),
    ]
