# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20160912_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.IntegerField(default=-1)),
                ('y1', models.IntegerField(default=-1)),
                ('x2', models.IntegerField(default=-1)),
                ('y2', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='gamestate',
            name='last_word_pos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.WordLoc'),
        ),
    ]
