# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20160913_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='last_word_pos',
            field=models.CharField(default='[]', max_length=150),
        ),
    ]
